### ISSUE TITLE
Unable to map List<T>

### ISSUE THREAD

**Issue by AleyCZ** [PavelLev/MappingSourceGenerator#15]
We are facing an issue which started to show in version 0.1.9 and is also present in 0.1.10. But it worked correctly in 0.1.8.

The error message is:
error MAPGEN1020: Return type System.Collections.Generic.List<MyRecord> of mapping method contains multiple public non-default constructors

I am trying to map a record a different record. The record contains another record inside it. And inside that one is List<T>. (Sorry, I did not try to find the minimal possible example, I am describing the real case.)

record MyRecord(int a, OtherRecord b);
record OtherRecord(int b, List<ThirdRecord> c);

All records are defined identically in two namespaces and I am trying to map one group to the same definitions in another namespace.

**Comment by PavelLev** [comment]
Please check 0.1.11, List<T> support should be restored

**Comment by AleyCZ** [comment]
I tried version 0.1.11, now the build issues lot of messages like this:

error CS9057: The analyzer assembly '...mappingsourcegenerator\0.1.11\analyzers\dotnet\cs\MappingSourceGenerator.dll' references version '4.9.0.0' of the compiler, which is newer than the currently running version '4.6.0.0'.

Isn't the library supposed to be compatible with .NET Standard 2.0? This version does seem to require .NET 8.

**Comment by PavelLev** [comment]
Sorry, I use Rider and it doesn't show this error. I've rolled back `Microsoft.CodeAnalysis.CSharp.Workspaces` package upgrade in 0.1.12, so now it should work

**Comment by AleyCZ** [comment]
Yes, it compiles without errors with version 0.1.12.
